// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGdAT3XxOczsLvnUZptnGEU5f9Uh9pj7k',
    appId: '1:966509849993:web:85e53ae3135259adafc558',
    messagingSenderId: '966509849993',
    projectId: 'flutterproject-379ae',
    authDomain: 'flutterproject-379ae.firebaseapp.com',
    databaseURL: 'https://flutterproject-379ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-379ae.appspot.com',
    measurementId: 'G-Z8845HCH21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXQv5T9BQBTQGzBUvgdFmc1c9mDFRzy4',
    appId: '1:966509849993:android:73225777cb3711caafc558',
    messagingSenderId: '966509849993',
    projectId: 'flutterproject-379ae',
    databaseURL: 'https://flutterproject-379ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-379ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4KCBfEByK85vXe6-EsgnWRBS2xoYkw-Y',
    appId: '1:966509849993:ios:40edef22cb3ff634afc558',
    messagingSenderId: '966509849993',
    projectId: 'flutterproject-379ae',
    databaseURL: 'https://flutterproject-379ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-379ae.appspot.com',
    iosClientId: '966509849993-rrk4kb3jltellmv3cc2lscd26dsqijlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4KCBfEByK85vXe6-EsgnWRBS2xoYkw-Y',
    appId: '1:966509849993:ios:40edef22cb3ff634afc558',
    messagingSenderId: '966509849993',
    projectId: 'flutterproject-379ae',
    databaseURL: 'https://flutterproject-379ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-379ae.appspot.com',
    iosClientId: '966509849993-rrk4kb3jltellmv3cc2lscd26dsqijlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );
}
